### ISSUE TITLE
Publishing when no repository set

### ISSUE THREAD

**Issue by scottmelhop** [tgolsson/pants-backends#75]
**Describe the bug**
When running the publish goal on `oci_image_build` it will try to publish images even if the `repository` argument is not set.

**To Reproduce**

```
oci_image_build(
    name="image",
    layers=[":layer"],
    base=["//:python-distroless-arm"],
    # repository=repository,
    # tag=image_tags,
    entrypoint="python3",
    args=[f"{dirctory_no_slash}/local.pex"],
    env=[
        f"PEX_PATH=/{dirctory_no_slash}/local.pex",
    ],
)
```

```pants publish ::```

**Expected behavior**
Ignore target when repository not set

**Setup (please complete the following information):**
 - https://github.com/tgolsson/pants-backends@064c00b67311675971449b51962ce62e766d500d#egg=pants_backend_oci&subdirectory=pants-plugins/oci
 - Pants version [e.g. `2.19.0`]
 - umoci nightly mac arm

**Comment by tgolsson** [comment]
Fixed in 0.6.1.
